### ISSUE TITLE
ReadTimeOut Error - 

### ISSUE THREAD

**Issue by DynaMc** [xros/jsonpyes#24]
Is there a way to set the timeout while using jsonpyes? 

I have very large sets of data to import and I'm only trying smaller files but yet still getting:
`elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='localhost', port=9200): Read timed out. (read timeout=10))
`
I still get this even when I'm trying it on a 24M file. I have some files which are up to a few GBs each which I would like to eventually import. 

Any help with this would be great, thank you.

**Comment by DynaMc** [comment]
So, this is not really jsonpyes related I now know. I need to chunk my files down.

**Comment by xros** [comment]
@DynaMc  Glad to hear that you had solved it by yourself.

[elasticsearch manual](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-transport.html)

> transport.tcp.connect_timeout
> 
> The socket connect timeout setting (in time setting format). Defaults to 30s.

As we can see, the default timeout of elasticsearch is set to be 30s . You can set it to be higher if necessary :smile:
