### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by SophiaHan6** [xros/jsonpyes#36]
Collecting jsonpyes
  Using cached https://files.pythonhosted.org/packages/5e/db/be9f716626f7d5fc1b83320eccda0f5d48c80efaf3b7b4e9339dcead115e/jsonpyes-1.3.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/67/tx0qhqqj59b04kxb_6kkzjt00000gn/T/pip-install-fy258ruc/jsonpyes/setup.py", line 25
        except Exception, e:
                        ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/67/tx0qhqqj59b04kxb_6kkzjt00000gn/T/pip-install-fy258ruc/jsonpyes/

**Comment by xros** [comment]
notice your python version. py3 or py2
